/**
 * @file_id FILE-MVX-AUTO-ROUTETREE-GEN-001
 * @artifact_kind implementation
 * @project_id PRJ-HERMES-UNCHAINED
 * @workspace_id WKS-MVX-ROOT
 * @app_id APP-BACKEND
 * @module_id MOD-IDE-WEB
 * @component_id COMP-ROUTETREE-GEN
 * @bounded_context governance
 * @epic_id EPI-MVX-00
 * @capability_id CAP-UNSPECIFIED
 * @story_id STORY-UNSPECIFIED
 * @task_id TASK-UNSPECIFIED
 * @sprint_id SPR-00
 * @release_slice_id RS-UNSPECIFIED-00
 * @requirement_refs REQ-MVX-000
 * @acceptance_refs AC-UNSPECIFIED-000
 * @test_refs TEST-UNSPECIFIED-000
 * @contract_refs CNTR-UNSPECIFIED
 * @evidence_refs EVD-UNSPECIFIED-000
 * @depends_on_files NONE
 * @used_by_files NONE
 * @schema_refs SCH-UNSPECIFIED-000
 * @event_refs EVT-UNSPECIFIED-000
 * @api_refs API-UNSPECIFIED-000
 * @flow_links flow:unspecified,ui:unspecified,event:unspecified
 * @telemetry trace:unspecified;metric:unspecified;log:unspecified
 * @dashboard_refs DASH-UNSPECIFIED
 * @alert_policy_refs ALT-UNSPECIFIED
 * @runbook_refs RB-UNSPECIFIED
 * @rollout_refs RO-UNSPECIFIED
 * @rollback_refs ROLLBACK-UNSPECIFIED
 * @security_class internal
 * @data_class technical_metadata
 * @pii_flag no
 * @auth_scope management_plane
 * @compliance_scope internal-audit
 * @retention_policy rp-persistent
 * @owner_team hermes-platform-team
 * @approver_role architect
 * @human_author architect/lucadeg
 * @agent_author codex
 * @generated_by_model gpt-5.3-codex
 * @prompt_hash sha256:auto-generated
 * @compiler_version mvx-tvm-v5
 * @source_artifacts AUTO-GENERATED
 * @generated_at 2026-05-13T13:53:39.867Z
 * @updated_at 2026-05-13T13:53:39.868Z
 * @hash sha256:b0050c3f5ec0855d5f87e6e2abf2d8e8f5e8a1afa250b94b755ac8b5a8827da6
 * @reviewers architect/lucadeg
 * @last_verified_at 2026-05-13T13:53:39.867Z
 * @review_state draft
 * @admissibility candidate
 * @impl_status_tmp_mock true
 */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as JsScriptDotjsRouteImport } from './routes/js/script[.]js'
import { Route as GuidesSplatRouteImport } from './routes/guides/$'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiEventRouteImport } from './routes/api/event'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const JsScriptDotjsRoute = JsScriptDotjsRouteImport.update({
  id: '/js/script.js',
  path: '/js/script.js',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSplatRoute = GuidesSplatRouteImport.update({
  id: '/guides/$',
  path: '/guides/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventRoute = ApiEventRouteImport.update({
  id: '/api/event',
  path: '/api/event',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/pricing': typeof MarketingPricingRoute
  '/api/event': typeof ApiEventRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/guides/$': typeof GuidesSplatRoute
  '/js/script.js': typeof JsScriptDotjsRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/pricing': typeof MarketingPricingRoute
  '/api/event': typeof ApiEventRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/guides/$': typeof GuidesSplatRoute
  '/js/script.js': typeof JsScriptDotjsRoute
  '/': typeof MarketingIndexRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/api/event': typeof ApiEventRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/guides/$': typeof GuidesSplatRoute
  '/js/script.js': typeof JsScriptDotjsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms-and-conditions'
    | '/pricing'
    | '/api/event'
    | '/api/subscribe'
    | '/guides/$'
    | '/js/script.js'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/terms-and-conditions'
    | '/pricing'
    | '/api/event'
    | '/api/subscribe'
    | '/guides/$'
    | '/js/script.js'
    | '/'
    | '/guides'
  id:
    | '__root__'
    | '/_marketing'
    | '/privacy'
    | '/terms-and-conditions'
    | '/_marketing/pricing'
    | '/api/event'
    | '/api/subscribe'
    | '/guides/$'
    | '/js/script.js'
    | '/_marketing/'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ApiEventRoute: typeof ApiEventRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  GuidesSplatRoute: typeof GuidesSplatRoute
  JsScriptDotjsRoute: typeof JsScriptDotjsRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/js/script.js': {
      id: '/js/script.js'
      path: '/js/script.js'
      fullPath: '/js/script.js'
      preLoaderRoute: typeof JsScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$': {
      id: '/guides/$'
      path: '/guides/$'
      fullPath: '/guides/$'
      preLoaderRoute: typeof GuidesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/event': {
      id: '/api/event'
      path: '/api/event'
      fullPath: '/api/event'
      preLoaderRoute: typeof ApiEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ApiEventRoute: ApiEventRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  GuidesSplatRoute: GuidesSplatRoute,
  JsScriptDotjsRoute: JsScriptDotjsRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
